config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
             controllers: {
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             }
  
  

  root "users#index"
  resources :users, only: [:index, :show, :edit, :update] do
    resources :posts, only: [:index, :new, :show, :create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable, :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal_to: 0

  has_one_attached :display_picture

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  def index
    render json: User.all
  end

  def show
    @user = User.find(params[:id])
    render json: { success: true, data: { user: @user, message: 'User found' } }
  end
end

app/controllers/users/registration_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    resource.persisted? ? register_success : register_failed
  end

  def register_success
    render json: { message: 'Signed up.' }
  end

  def register_failed
    render json: { message: 'Signed up failure.' }
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(_resource, _opts = {})
    render json: { message: 'Logged in.' }, status: :ok
  end

  def respond_to_on_destroy
    current_user ? log_out_success : log_out_failure
  end

  def log_out_success
    render json: { message: 'Logged out.' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Logged out failure.' }, status: :unauthorized
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index show]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :display_picture)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Zeblog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="d-flex">
      <% if user_signed_in? %>
        <%= link_to "All Users", root_path, class: "nav-link" %>
        <%= link_to 'All Posts', {:action => 'index'}, class: 'nav-link'%>
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'%>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/users/_recent_posts.html.erb
<h2 class="pb-2 border-bottom text-center">Recent Posts</h2>
<% @user.recent_posts.each do |post| %>
<div class="card">
  <div class="card-body py-5 px-md-5">
    <%= link_to user_post_path(@user.id, post.id) do %>
          <h4 class="text-center"><%= post.title %></h4>
      <% end %>
    <blockquote class="text-sm-left">
      <p class="text-sm-left"><%= post.text%></p>
      <h3>Comment <%= post.comments.count%>,  <span>Likes <%= post.likes.count%></span></h3>
      <p class="card-text text-start">Posted <%= time_ago_in_words(post.created_at)%> ago</p>
    </blockquote>
   </div>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'navbar'%>
<section class="posts">
    <% if @users.blank? %>
        <p>There are no users currently in the system.</p>
    <% else %>
    <div class="card">
    <h5 class="card-header text-center">Poeple you may know</h5>
        <% @users.each do |user| %>
        <div class="card-body">
            <div class="row px-5">
                <div class="col rounded float-start">
                <%= image_tag("profile.jpg", :alt => "User icon")%>
                </div>
                <div class="col">
                <%= link_to user.name, user_path(user.id) %>
                </div>
                <p class="col">Number of posts: <span><%= user.posts.count %></span></p>
            </div>
        </div>
        <% end %>
    </div>
    <% end %>
</section>

app/views/users/show.html.erb
<%= render 'navbar'%>
<div class="posts">
    <div class="user">
      <div class="col-md-2 img-thumbnail">
        <%= image_tag("profile-placeholder.png", :alt => "User icon") %>
       </div>
    <blockquote class="blockquote mb-0">
      <%= @user.name %>
      <p><%= @user.bio%></p>
      <footer class="blockquote-footer"><cite title="Source Title">Wrote <%= @user.posts.count %> posts</cite></footer>
      <%= link_to "All posts", user_posts_path(@user), class: "btn btn-primary" %>
    </blockquote>
  
  </div>
</div>
 <%= render 'recent_posts'%>